language: cpp
dist: bionic
sudo: required

os:
  - osx

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update > /dev/null
    && brew install qt5 > /dev/null
    && brew install openssl > /dev/null
    && export PATH=/usr/local/opt/qt5/bin/:$PATH
    ;
    fi
  - qmake -v

before_script:
    - git clone --recursive https://github.com/uglide/RedisDesktopManager.git rdm
    - pushd rdm
    - git checkout -b 2019.5 2019.5 && git submodule update --init --recursive
    - mkdir -p /usr/local/opt/python/lib/Python.framework/Versions/
    - ln -s /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7 /usr/local/opt/python/lib/Python.framework/Versions/3.7
    - popd

script:
  - ./build.sh

deploy:
  provider: releases
  api_key: ${DEPLOY_KEY}
  file: 'rdm/bin/osx/release/Redis Desktop Manager.dmg'
  skip_cleanup: true
  draft: true
  on:
    tags: true

after_success:
  - echo "build success"
